site_name: ValidationPy

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - ValidationPy Docs: index.md
  - Tutorials: tutorials.md
  - How-To Guides: how-to-guides.md
  - Reference: reference.md
  - Explanation: explanation.md
